feat: prefix STATUS and PREEXEC_READY shell vars with STARSHIP_
starship/starship pull request #1710
Opened 2020-10-01 06:40 UTC by bjornfor

#### Description
I was surprised to see the STATUS and PREEXEC_READY variables being set in my shell. I think
it's better to have them in the STARSHIP_ "namespace". (Actually, STATUS
got the new name STARSHIP_CMD_STATUS.)

#### Motivation and Context
For cleanliness :-) And it's unfortunate if users try to use the generic name `STATUS` for themself, not knowing starship will overwrite the variable. 

#### Screenshots (if appropriate):

#### How Has This Been Tested?
* I ran `cargo test`:
  - on master: `test result: FAILED. 415 passed; 47 failed; 26 ignored; 0 measured; 0 filtered out`
  - on this PR: `test result: FAILED. 415 passed; 47 failed; 26 ignored; 0 measured; 0 filtered out`
* I installed starship from this PR onty my system (with bash).

- [ ] I have tested using **MacOS**
- [x] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly. (I didn't see any documentation regarding to these variables, I think they are an implementation detail. The remaining uses of `STATUS` in the repo seem unrelated to this change, so I left it alone.)
- [ ] I have updated the tests accordingly. (AFAICS, no tests need updating.)

2020-12-12 19:53 UTC, bjornfor commented
The macOS test failed in the CI, but I don't think it has anything to do with this PR:

```
test modules::hg_branch::tests::test_hg_disabled_per_default ... ok

failures:

---- modules::directory::tests::truncation_symbol_not_truncated_home stdout ----
thread 'modules::directory::tests::truncation_symbol_not_truncated_home' panicked at 'assertion failed: `(left == right)`
  left: `Some("\u{1b}[1;36m~/.tmpSuxaY7/a/subpath\u{1b}[0m ")`,
 right: `Some("\u{1b}[1;36m…/.tmpiu1BJg/.tmpSuxaY7/a/subpath\u{1b}[0m ")`', src/modules/directory.rs:1330:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    modules::directory::tests::truncation_symbol_not_truncated_home

test result: FAILED. 519 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 4.10s

error: test failed, to rerun pass '--lib'
Error: Process completed with exit code 101.
```

2020-12-12 21:44 UTC, bjornfor commented
Seems CI is a bit flaky, it worked on the 2nd try.

2020-12-12 22:56 UTC, chipbuster commented
@bjornfor Yeah, our CI has some known issues, but I've never been able to replicate the problems locally. As far as I can tell, the only person who's ever triggered the race condition while on their own hardware was someone who was on an s390x with ~200 hardware threads. For the time being, we just rebuild when a race gets triggered.

2020-12-15 16:59 UTC, nesara-cmd requested changes

2020-12-15 16:59 UTC, nesara-cmd commented on src/init/starship.bash
>          STARSHIP_START_TIME=$(::STARSHIP:: time)
[]()

2020-12-15 16:59 UTC, nesara-cmd commented on src/init/starship.bash
> -# start the timer if this flag is present. That way, timing is for the entire command,
[]()

2020-12-15 17:01 UTC, nesara-cmd commented on src/init/starship.bash
> -# start the timer if this flag is present. That way, timing is for the entire command,
131220

2020-12-16 03:32 UTC, chipbuster approved these changes
CI doesn't test changes to the init scripts, so I checked this out and tested it locally. Pleased to report that everything is working.

2020-12-19 11:04 UTC, merged

2020-12-19 11:04 UTC, andytom commented
Thank you for your contribution @bjornfor.

2020-12-19 12:20 UTC, bjornfor commented
Thanks!