fix: Adjust default format strings
starship/starship pull request #2165
Opened 2021-01-19 03:51 UTC by HansAuger

#### Description
Adjust format strings for all modules where format is already lazily executed

#### Motivation and Context

Referring to #2111

#### How Has This Been Tested?

- [x] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [x] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

2021-01-19 17:21 UTC, andytom requested changes

2021-01-19 17:21 UTC, andytom commented on src/configs/erlang.rs
> +            format: "via [$symbol$version ]($style)",
And here
```suggestion
            format: "via [$symbol($version )]($style)",
```

2021-01-19 17:21 UTC, andytom commented on src/configs/go.rs
> +            format: "via [$symbol$version ]($style)",
```suggestion
            format: "via [$symbol($version )]($style)",
```

2021-01-19 17:21 UTC, andytom commented on src/configs/rust.rs
> +            format: "via [$symbol$version ]($style)",
```suggestion
            format: "via [$symbol($version )]($style)",
```

2021-01-19 17:21 UTC, andytom commented on src/configs/ruby.rs
> +            format: "via [$symbol$version ]($style)",
```suggestion
            format: "via [$symbol($version )]($style)",
```

2021-01-19 17:21 UTC, andytom commented on src/configs/nim.rs
> +            format: "via [$symbol$version ]($style)",
```suggestion
            format: "via [$symbol($version )]($style)",
```

2021-01-19 17:21 UTC, andytom commented on src/configs/helm.rs
> +            format: "via [$symbol$version ]($style)",
```suggestion
            format: "via [$symbol($version )]($style)",
```

2021-01-19 17:21 UTC, andytom commented on src/configs/julia.rs
> +            format: "via [$symbol$version ]($style)",
```suggestion
            format: "via [$symbol($version )]($style)",
```

2021-01-20 02:16 UTC, HansAuger commented on docs/config/README.md
> +| `format`   | `"via [$symbol$version ]($style)"` | The format for the module.                      |
```suggestion
| `format`   | `"via [$symbol($version )]($style)"` | The format for the module.                      |
```

2021-01-20 02:16 UTC, HansAuger commented on docs/config/README.md
> +| `format`   | `"via [$symbol$version ]($style)"` | The format for the module.                       |
```suggestion
| `format`   | `"via [$symbol($version )]($style)"` | The format for the module.                       |
```

2021-01-20 02:16 UTC, HansAuger commented on docs/config/README.md
> +| `format`   | `"via [$symbol$version ]($style)"` | The format for the module                             |
```suggestion
| `format`   | `"via [$symbol($version )]($style)"` | The format for the module                             |
```

2021-01-20 02:17 UTC, HansAuger commented on docs/config/README.md
> +| `format`   | `"via [$symbol$version ]($style)"` | The format for the module.                        |
```suggestion
| `format`   | `"via [$symbol($version )]($style)"` | The format for the module.                        |
```

2021-01-20 02:17 UTC, HansAuger commented on docs/config/README.md
> +| `format`   | `"via [$symbol$version ]($style)"` | The format for the module.                       |
```suggestion
| `format`   | `"via [$symbol($version )]($style)"` | The format for the module.                       |
```

2021-01-20 02:17 UTC, HansAuger commented on docs/config/README.md
> +| `format`   | `"via [$symbol$version ]($style)"` | The format for the module.                     |
```suggestion
| `format`   | `"via [$symbol($version )]($style)"` | The format for the module.                     |
```

2021-01-20 02:17 UTC, HansAuger commented on docs/config/README.md
> +| `format`   | `"via [$symbol$version ]($style)"` | The format for the module.                               |
```suggestion
| `format`   | `"via [$symbol($version )]($style)"` | The format for the module.                               |
```

2021-01-20 02:18 UTC, HansAuger commented on docs/config/README.md
> +| `format`    | `"[$symbol$version (🎯 $tfm )]($style)"`  | The format for the module.                               |
```suggestion
| `format`    | `"[$symbol($version )(🎯 $tfm )]($style)"`  | The format for the module.                               |
```

2021-01-20 02:20 UTC, HansAuger commented
Must have been drunk xD
Resolved!

2021-01-20 17:46 UTC, andytom approved these changes
LGTM

2021-01-20 17:46 UTC, merged

2021-01-20 17:46 UTC, andytom commented
Thanks for sorting this out @HansAuger