feat(scala): Add scala module
starship/starship pull request #2409
Opened 2021-03-03 12:29 UTC by bbenzikry

#### Description

Add a module for identifying scala version. 
Tested on scala 2 + dotty/scala 3

#### Motivation and Context

As a starship user, I'd like to be able to see my current scala version while happily traversing projects. 
Closes #651 ( at least partially ) 

It's important to note that: 
* Scala tooling is a bit on the slow side, so it may require changing ``command_timeout``, especially when using version shims like asdf

```
Benchmark #1: ./scala -version
  Time (mean ± σ):     536.7 ms ±  73.6 ms    [User: 703.9 ms, System: 101.9 ms]
  Range (min … max):   504.6 ms … 745.4 ms    10 runs

Benchmark #1: ./scalac -version
  Time (mean ± σ):     397.4 ms ±   5.2 ms    [User: 536.2 ms, System: 86.3 ms]
  Range (min … max):   390.3 ms … 408.0 ms    10 runs

Benchmark #1: starship module scala
  Time (mean ± σ):     402.6 ms ±   4.7 ms    [User: 540.2 ms, System: 90.5 ms]
  Range (min … max):   397.4 ms … 411.3 ms    10 runs
```
* This PR does not support sbt / project versions, as versions can be defined in a lot of different ways and sbt itself is slow ( at least during my tests ) to the point where I feel it won't be usable. 

```
Benchmark #1: sbt sbtVersion | tail -1 | awk '{print }'
  Time (mean ± σ):      4.730 s ±  0.137 s    [User: 14.113 s, System: 1.405 s]
  Range (min … max):    4.514 s …  4.984 s    10 runs
```

It may be possible to check ``project/build.properties`` but I believe it should be in a seperate PR that deals with the perf issues more thoroughly. 

#### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/1993348/109793227-0da8e380-7c1d-11eb-8682-20fce437c743.png)

#### How Has This Been Tested?

- [x] I have tested using **MacOS**
- [x] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [x] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

2021-03-10 06:18 UTC, vladimyr requested changes
Looks good! :+1:

2021-03-10 06:18 UTC, vladimyr commented on src/modules/scala.rs
> +use std::fs;
This is unused. as Clippy already reported:
```suggestion
```

2021-03-10 06:18 UTC, vladimyr commented on src/modules/scala.rs
> +const SCALA_VERSION_PATTERN: &str = "version[\\s](?P<version>[0-9\\.\\-A-z]+)";
You can rely on a fact that version can't contain whitespace:
```suggestion
const SCALA_VERSION_PATTERN: &str = "version[\\s](?P<version>[^\\s]+)";
```

2021-03-10 06:18 UTC, vladimyr commented on src/modules/scala.rs
> +    let output = context.exec_cmd(&scala_command.as_str(), &["-version"])?;
This can be simplified to:
```suggestion
    let output = context.exec_cmd("scalac", &["-version"])?;
```

2021-03-10 06:18 UTC, vladimyr commented on src/modules/scala.rs
> +    use std::fs::File;
```suggestion
    use std::fs::{self, File};
```

2021-03-10 06:47 UTC, vladimyr approved these changes

2021-03-14 18:32 UTC, davidkna commented on docs/config/README.md
> +| `symbol`            | `"🆂 "`                                    | format string representing the symbol of Scala   |
```suggestion
| `symbol`            | `"🆂 "`                                    | A format string representing the symbol of Scala.   |
```

2021-03-14 19:36 UTC, davidkna approved these changes

2021-03-14 19:37 UTC, merged

2021-03-14 19:37 UTC, davidkna commented
Thanks for the contribution @bbenzikry and thanks for reviewing @vladimyr.