feat(red): create module
starship/starship pull request #2599
Opened 2021-04-17 19:02 UTC by Milo123459

#### Description

Adds a module for Red
#### Motivation and Context

Closes #

#### Screenshots (if appropriate):
![img](https://salvage.is-inside.me/99Z8pKp3.png)
#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [x] I have tested using **Windows**

#### Checklist:

- [x] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

2021-04-17 20:11 UTC, vladimyr commented
> `fmt even though i already did it`
💯

2021-04-18 15:45 UTC, vladimyr requested changes
LGTM, just a couple of small fixes left.
Also, please post hyperfine stats for `red --version` invocation.

2021-04-18 15:45 UTC, vladimyr commented on docs/config/README.md
> +[ruby]
```suggestion
[red]
```

2021-04-18 15:45 UTC, vladimyr commented on src/modules/red.rs
> +                    .and_then(|output| parse_red_version(output.stdout.trim()))
Use `.map` here instead so you can get rid of unnecessary option wrap.

2021-04-18 15:45 UTC, vladimyr commented on src/modules/red.rs
> +fn parse_red_version(red_version: &str) -> Option<String> {
Return `String` instead.

2021-04-18 15:47 UTC, Milo123459 commented on docs/config/README.md
> +[ruby]
My bad, as per usual...

2021-04-19 10:36 UTC, vladimyr requested changes

2021-04-19 10:36 UTC, vladimyr commented on docs/config/README.md
> +- The current directory contains a file ending with `.red` or `.reds`
Follow wording style set by other doc sections:
```suggestion
- The current directory contains a file with `.red` or `.reds` extension
```

2021-04-19 10:36 UTC, vladimyr commented on src/modules/red.rs
> +                    .and_then(|output| parse_red_version(output.stdout.trim()))
This is still actual 🙃

2021-04-19 10:36 UTC, vladimyr commented on src/modules/red.rs
> +fn parse_red_version(red_version: &str) -> Option<String> {
Avoid adding clippy warning overrides - simply return a `String`.

2021-04-20 01:52 UTC, vladimyr commented
@Milo123459 Please apply this patch https://github.com/vladimyr/starship/commit/0d7c53c.patch

2021-04-20 13:03 UTC, vladimyr approved these changes
@Milo123459 Thanks for your great work and patient walk through this review journey!

LGTM

2021-04-20 16:31 UTC, merged

2021-04-20 16:32 UTC, andytom commented
Thank you @Milo123459 for your contribution and as always thank you for reviewing @vladimyr.