Fix #3243
starship/starship pull request #3244
Opened 2021-11-17 04:00 UTC by haoadoresorange

Something like this ?

2021-11-17 08:35 UTC, matchai commented
Please update your PR to use the provided PR template.

2021-11-18 03:48 UTC, haoadoresorange commented
updated !

2021-11-30 05:06 UTC, haoadoresorange commented
@matchai can you review it please ?

2021-12-29 05:13 UTC, chipbuster requested changes
For some reason, GitHub will not let me make individual review comments on this PR (literally just this PR, other PRs work fine), so you get one giant blob comment instead of any sane sort of breakdown.

Line numbers refer to lines in the proposed changes unless otherwise stated.

### Using `has`

On line 158, you use both `sha256sum` and `awk` to generate the checksum. I'd like to see these wrapped in a check to `has` (see e.g. line 46 where we use it to check if mktemp exists).

I honestly don't expect that it'll ever actually trigger, but we do support some relatively rare platforms, and I'd like to make sure we get a graceful message if we don't have those tools.

### Double brackets

This install script is intended to be run as a POSIX script, so double brackets (`[[` `]]`) are not supported.

### Failure behaviour

Right now, if the checksums don't match, the install script will print "Starship installed" (line 498) without actually installing anything. This isn't great. (This will also become an issue when you add `has` checks from the first section: what will you do if those checks fail?)

Ideally I'd like to see an interactive option to continue, paired with a command line option (e.g. `--no-checksum`) which allows a user to skip checksum validation pre-emptively. However, I would also accept just printing an error message and exiting the script immediately---something that isn't saying "Install successful" without actually installing anything.

2026-04-30 19:56 UTC, closed without merging