Fixed starship config location
starship/starship pull request #3432
Opened 2022-01-14 10:18 UTC by BRAVO68WEB

#### Description
config file during creation and when used as export variable into shells are different.
Fixed to make it uniform and avoid errors

#### Motivation and Context
I was installing starship today while reading the documentation for the same.
The configuration file location while creation and when it was exported to shells were different.
[here](https://starship.rs/config/#configuration)  

#### Checklist:
- [x] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

2022-01-14 10:27 UTC, davidkna commented
To fix the Semantic Pull Request check, you can either add another commit with any commit message or change the first commit message to conform to semantic commit guidelines by prepending `docs: ` to the commit message, e.g.

```
git commit --allow-empty -m 'make Semantic PR bot happy'
git push 
```

2022-01-14 11:35 UTC, andytom requested changes
This is incorrect the default starship configuration file is `~/.config/starship.toml`, I think the confusion is coming from the example of using the `STARSHIP_CONFIG` environment variable to set a different location for the configuration file.

2022-01-14 12:21 UTC, matchai commented
This isn't the first time that example has lead to confusion. I think it's time we change the example to be distinctly intentionally different.

2022-01-14 15:11 UTC, BRAVO68WEB commented
Ok I am do the requested changes

2022-01-14 21:29 UTC, andytom commented on docs/config/README.md
> +export STARSHIP_CONFIG=~/.config/starship.toml
I think this should be something like

```suggestion
export STARSHIP_CONFIG=~/example/non/default/path/starship.toml
```

To make it explicit that this is just an example.

2022-01-14 21:29 UTC, andytom commented on docs/config/README.md
> +$ENV:STARSHIP_CONFIG = "$HOME\.config/starship.toml"
And here

```suggestion
$ENV:STARSHIP_CONFIG = "$HOME\example\non\default\path\starship.toml"
```

2022-01-14 21:29 UTC, andytom commented on docs/config/README.md
> +os.setenv('STARSHIP_CONFIG', 'C:\\Users\\user\\.config\\starship.toml')
Here too

```suggestion
os.setenv('STARSHIP_CONFIG', 'C:\\Users\\user\\example\\non\\default\\path\\starship.toml')
```

2022-01-15 03:42 UTC, BRAVO68WEB commented
Added suggested changes

2022-01-15 10:30 UTC, andytom approved these changes

2022-01-15 10:35 UTC, merged