feat: edit the bug report before submission
starship/starship pull request #3794
Opened 2022-03-26 16:04 UTC by IsaacHorvath

#### Description
This pull request changes the behaviour of `starship bug-report` to drop into the system editor and allow the user to edit the bug report before populating the GitHub post. An empty bug report cancels the post. I've also added a `-p` `--print` flag to dump the report to stdin instead of posting, as requested in the issue.

Note: This PR adds a crate: [`edit`](https://crates.io/crates/edit).

#### Motivation and Context
To allow for better privacy and control over data submitted in bug reports.
Closes #3757 

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [x] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [x] I have updated the tests accordingly.
- [ ] I have updated the documentation accordingly. 
_I can't find any documentation for `starship bug-report`_

2022-03-26 16:06 UTC, davidkna commented
You can probably use `open` instead of `edit`

2022-03-26 17:06 UTC, IsaacHorvath commented
I used `edit` because it automatically uses a system temporary file, has more robust means of finding a system editor, and the code is a lot more concise - this block handles the whole edit process:
```
    let report = match edit::edit(report) {
        Ok(r) => r,
        Err(e) => {
            println!("Error editing bug report: {}", e);
            return;
        }
    };
```
However, if you want to keep a tighter supply chain, I'm happy to abstract out the code in the configure module and rebuild using that. Alternatively, I could clean up `configure.rs` and have it use `edit` as well for simplicity's sake.

2022-03-26 17:11 UTC, davidkna commented
`edit` looks nice, but it doesn't seem to properly handle shell quoting, and it doesn't seem to be very popular.

2022-04-21 19:12 UTC, davidkna requested changes

2022-04-21 19:12 UTC, davidkna commented on src/utils.rs
> +        .status();
I'd prefer improving error handling on editing before going forward with this change (https://github.com/starship/starship/issues/3758 #3766)

2022-04-21 19:12 UTC, davidkna commented on src/bug_report.rs
> +    };
Please print a message before exiting, or preferably just accept empty reports?

2022-04-21 19:12 UTC, davidkna commented on src/bug_report.rs
> +    };
Perhaps ask for confirmation before sending? Some editors might not wait for exit like `code` without `--wait`.

A flag for skipping editing in general might be good too (and reference it in relevant error messages).

2022-04-21 19:12 UTC, davidkna commented on src/utils.rs
> +pub fn edit(path: OsString) {
Why not `&Path`?

2022-04-21 19:13 UTC, davidkna commented
Please also rebase this PR to add the codecov check.

2022-11-25 16:44 UTC, closed without merging