feat: add npm module
starship/starship pull request #3937
Opened 2022-04-28 05:02 UTC by sambehrens

#### Description

This adds the npm module so that when in a directory with a
package-lock.json or an .npmrc, you will see the npm version displayed.
Usually this will be after the nodejs module because by default the
nodejs module will display if there is a package.json and where there is
a package-lock.json, there is almost always a package.json.

The npm module is disabled by default because it can add extra unwanted
noise to your prompt. However it can also be very useful to have in your
prompt because npm is known for having different behaviors between major
versions that will subtly break your project.

This also mimics the nodejs module when it comes to checking the
engines field in package.json. The default color is a dark red, and if
the current npm version is incompatible with the engines field in the
local package.json, it will display as the default red, to match the
color of the nodejs module when it is incompatible. Yes, npm's color is
red and when there is an error it is just a lighter red, but I didn't
know what color to make npm by default and still have an error color
that made sense 😅 .

#### Motivation and Context

As a developer who works in the node ecosystem often, I find it to be very
useful to know what version of npm that I'm on at all times. It is not so much of a problem with
other package managers like yarn and pnpm etc. but npm often breaks things
between major versions and different projects require different versions so
having the npm version available in my prompt would be very useful.

Closes #557

#### Screenshots (if appropriate):

#### How Has This Been Tested?

This module is very very similar to the nodejs module so I essentially modified the
tests that that module has to work with the npm module.

- [x] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [x] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

2022-06-04 11:07 UTC, davidkna requested changes

2022-06-04 11:07 UTC, davidkna commented on src/configs/npm.rs
> +            symbol: " ",
Please use an emoji or a plain-text symbol here.

2022-06-04 11:07 UTC, davidkna commented on src/configs/npm.rs
> +            symbol: " ",
Please use an emoji or a plain-text symbol here.

2022-06-04 11:07 UTC, davidkna commented on src/modules/npm.rs
> +
Modules that are disabled by default require an explicit check for `config.disabled`.

2022-06-04 11:07 UTC, davidkna commented on src/modules/npm.rs
> +
Modules that are disabled by default require an explicit check for `config.disabled`.

2022-06-04 11:27 UTC, davidkna commented
Sorry for the late review, please implement my suggestions to get this ready to merge.

2022-10-23 11:23 UTC, davidkna commented
See discussion in https://github.com/starship/starship/issues/557

2022-10-23 11:23 UTC, closed without merging

2022-11-08 06:06 UTC, sambehrens commented
Hey, sorry this totally fell off my radar but I'm willing to update the mr as I'm still interested in getting this feature.