feat(container): Allow use of podman container name instead of image name
starship/starship pull request #4243
Opened 2022-08-09 09:48 UTC by Fuzzy-Math

#### Description

This PR adds configuration in the container module to allow displaying the container name instead of the container image. This is useful for when many containers share the same image (ie. toolbox containers). To enable, add the following to starship.toml
```
[container]
use_container_name = true
```

Closes #3592

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [X] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [X] I have updated the documentation accordingly.
- [X] I have updated the tests accordingly.

2022-09-27 15:36 UTC, davidkna requested changes

2022-09-27 15:36 UTC, davidkna commented on src/modules/container.rs
> +                            if config.use_container_name && line.starts_with("name") {
Please change this to only iterate once over the lines.

2022-09-27 15:36 UTC, davidkna commented on src/modules/container.rs
> +                                Some(String::from(name.trim_matches('"')))
Would `shellwords::split`work here?

2022-09-27 15:36 UTC, davidkna commented on src/configs/container.rs
> +    pub use_container_name: bool,
Perhaps call this `prefer_container_name` instead, your code seems to include a fallback.

2022-11-20 16:05 UTC, spencergilbert commented
I'd personally suggest the current behavior is a bug, or at least contradicting the documentation of the feature. I find the actual container name to be more useful to me than the name of the image, but it seemed like that is split between users - perhaps a configuration to toggle between the two is a good compromise.

2024-03-30 13:37 UTC, closed without merging

2024-03-30 13:38 UTC, andytom commented
Closing this PR as it has been superceded by a few others.