feat(module): Add a meson devenv indicator
starship/starship pull request #4389
Opened 2022-09-20 23:47 UTC by ItsJamie9494

#### Description
Adds a Meson Developer Environment indicator, if the `$MESON_DEVENV` and `$MESON_PROJECT_NAME` variables are set.
Inside a `meson devenv`, the prompt will include the current Meson project name, in similar fashion to a container. The name is retrieved from the `$MESON_PROJECT_NAME` variable.

#### Motivation and Context
A meson dev environment changes some environment variables for testing an application without installing to the root system. A full list of changes can be found at https://mesonbuild.com/Release-notes-for-0-58-0.html#developer-environment
Since variables such as the system PATH are being modified, I believe it is necessary to show that I am using a custom environment.
You can think of this as similar to a Python virtual environment, and how that is supported in Starship.

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [x] I have tested using **Linux**
- [ ] I have tested using **Windows**

I use Linux primarily, and have only tested on Linux, however I added multiple tests to check the output of this module, as well as tested it by loading Starship in a fresh `bash` shell without Starship initialised, and creating a Meson devenv. With my PR added, and minimal modifications to my `starship.toml`, my prompt was changed to show my environment.

#### Checklist:
- [x] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

I did copy the truncation code from the Git Branch module, and was wondering if it would be a good idea to eventually port that code into it's own util function, as it's now spread between two modules.

2022-10-03 12:29 UTC, davidkna reviewed
Thanks for the PR, I've made a few suggestions. Please also update the presets in `docs/.vuepress/public/presets/toml`.

2022-10-03 12:29 UTC, davidkna commented on docs/config/README.md
> +| `format`            | `"in [$symbol$project]($style) "` | The format for the module.                                                                |
I think this module would fit a bit better on the first line along with the conda module. Please also use `via` instead of `in` to match it.

2022-10-03 12:29 UTC, davidkna commented on src/modules/meson.rs
> +            Color::Blue.bold().paint("⬢ starship")
Does this still need to be handled?
```suggestion
            Color::Blue.bold().paint("⬢ starship")
```

2022-10-03 15:55 UTC, ItsJamie9494 commented on src/modules/meson.rs
> +    }
Would you like me to move the truncation code in this MR?

2022-10-03 16:19 UTC, davidkna commented on src/modules/meson.rs
> +    }
Either way is fine with me. I would also be fine with leaving this as-is for now.

2022-10-03 16:26 UTC, ItsJamie9494 commented on src/modules/meson.rs
> +    }
I'll move the code into a truncation utility for this module, but won't touch other modules

2022-10-04 06:31 UTC, ItsJamie9494 commented on src/configs/meson.rs
> +            truncation_length: std::i64::MAX,
```
---- configs::test::test_all_modules_in_full_config stdout ----
thread 'configs::test::test_all_modules_in_full_config' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("u64 value was too large")', src/configs/mod.rs:263:63
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

2022-10-04 06:34 UTC, ItsJamie9494 commented
I've added a `src/modules/utils/truncate.rs` file containing the truncation code. I think a different PR made in the future could convert other modules to using this truncation util instead of handling it themselves.

2022-10-04 06:39 UTC, ItsJamie9494 commented on src/configs/meson.rs
> +            truncation_length: std::i64::MAX,
Update: it seems to work with a usize?

2022-10-04 06:45 UTC, ItsJamie9494 commented
Not sure exactly what’s going on with the doc format check

2022-10-06 17:06 UTC, davidkna commented
@ItsJamie9494 Did you run [dprint](https://dprint.dev) to format it?

2022-10-06 17:09 UTC, ItsJamie9494 commented on src/configs/meson.rs
> +            truncation_length: std::i64::MAX,
I’ll try that again

2022-10-07 19:32 UTC, davidkna requested changes
I have two more requests, but apart from those LGTM.

2022-10-07 19:32 UTC, davidkna commented on docs/config/README.md
> +| `truncation_length` | `2^63 - 1`                         | Truncates a project name to `N` graphemes.                                                |
```suggestion
| `truncation_length` | `2^32 - 1`                         | Truncates a project name to `N` graphemes.                                                |
```

2022-10-07 19:32 UTC, davidkna commented on src/modules/meson.rs
> +    }
I would prefer a few more tests here:
```suggestion
    }

    #[test]
    fn env_invalid_devenv() {
        let actual = ModuleRenderer::new("meson")
            .env("MESON_DEVENV", "0")
            .env("MESON_PROJECT_NAME", "starship")
            .collect();

        let expected = None;

        assert_eq!(expected, actual);
    }

    #[test]
    fn env_invalid_project_name() {
        let actual = ModuleRenderer::new("meson")
            .env("MESON_DEVENV", "1")
            .env("MESON_PROJECT_NAME", " ")
            .collect();

        let expected = None;

        assert_eq!(expected, actual);
    }
```

2022-10-07 21:27 UTC, davidkna approved these changes

2022-10-11 16:02 UTC, merged