fix: check that BP_PIPESTATUS is defined
starship/starship pull request #4568
Opened 2022-11-05 00:54 UTC by raffaem

#### Description
Check that BP_PIPESTATUS is defined before operating on it.

#### Motivation and Context

If `set -u` to treat undefined parameters as error during parameters expansion, you will get an error at every command.

Closes #4567.

#### Screenshots (if appropriate):

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [X] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

2022-11-05 07:33 UTC, raffaem commented
This is failing to the the linting of code that is not mine

2022-11-05 13:28 UTC, andytom commented
> This is failing to the the linting of code that is not mine


I've merged the latest clippy fixes so if you rebase your branch that should (hopefully) fix them.

2022-11-09 15:43 UTC, chipbuster requested changes
In its current state, this PR breaks my bash due to missing spaces around the double bracket operators.

Even with the suggested changes, the issue with unbound `BP_PIPESTATUS` variable is not fixed on my system.

I am testing under bash 5.2.2(1).

2022-11-09 15:43 UTC, chipbuster commented on src/init/starship.bash
> +	if [[! -z "${#BP_PIPESTATUS[@]}"]]; then
```suggestion
	if [[ ! -z "${#BP_PIPESTATUS[@]}" ]]; then
```

2022-11-09 15:43 UTC, chipbuster commented on src/init/starship.bash
> +		if [["${#BP_PIPESTATUS[@]}" -gt "${#STARSHIP_PIPE_STATUS[@]}" ]]; then
```suggestion
		if [[ "${#BP_PIPESTATUS[@]}" -gt "${#STARSHIP_PIPE_STATUS[@]}" ]]; then
```

2022-12-31 13:14 UTC, closed without merging