fix(container): improved display of container for podman and systemd confusion
starship/starship pull request #4832
Opened 2023-01-17 21:26 UTC by bsherman

#### Description
Ubuntu's LTS images include  `/run/systemd/container` with contents `docker` and were detected as Systemd because that code ran before podman detection. 

Details:
- the module's podman containerenv detection and processing now happens before systemd detection (provides the expected behavior for image running in podman, even when the `/run/systemd/container` file exists)
- if `/run/systemd/container` contains "docker", the module now shows "Docker" (the expected behavior for image running in docker)
- maintains behavior from #4593 to prevent 'Systemd' display on WSL
- refactors tests for systemd detection for general cleanup of duplicate test code

#### Motivation and Context
Closes #3821 

Does NOT address PR#3828's  related changes for docker detection, but I see that as a distinct concern from the actual bug report.

#### How Has This Been Tested?
I added relevant test and ensured existing tests addressed the changes.
All tests pass (plus clippy and rustfmt were run per contribution guidelines).

I tested on Fedora with distrobox running on podman with both Fedora and Ubuntu images.
I tested on Ubuntu with distrobox running on docker with an Ubuntu image.
I tested on Windows 10 with Ubuntu in WSL to verify I didn't break that.

- [ ] I have tested using **MacOS**
- [x] I have tested using **Linux**
- [x] I have tested using **Windows**

#### Checklist:
- [ ] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

2023-01-20 11:02 UTC, davidkna requested changes

2023-01-20 16:59 UTC, bsherman commented on src/modules/container.rs
> +        };
Thank you for the feedback! Fixing this the way I'd originally intended, by passing `None` to the function. Codecov caught the bug!

2023-01-20 17:00 UTC, bsherman commented on src/modules/container.rs
> +            }
Updating incoming to both read once (instead of check then read) and to return directly from match.

2023-01-21 17:58 UTC, davidkna approved these changes
LGTM

2023-01-22 22:36 UTC, merged

2023-01-22 22:37 UTC, andytom commented
Thank you for your contribution @bsherman and thanks for the review @davidkna.