feat(aws): add support for source_profile
starship/starship pull request #4859
Opened 2023-01-26 23:49 UTC by devmatteini

#### Description

Display `AWS` module when setting `AWS_PROFILE` that uses `source_profile` in the config file.

#### Motivation and Context

Closes #3834

#### Screenshots (if appropriate):

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [x] I have tested using **Linux**
- [ ] I have tested using **Windows**

The rust tests are passing, but I couldn't make it work by running the actual executable from `cargo build`. I'm probably missing something, but couldn't find any documentation on how to do it properly.
Any help is appreciated!

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

2023-02-16 07:38 UTC, luiscamaral requested changes
Minor comment

2023-02-16 07:38 UTC, luiscamaral commented on src/modules/aws.rs
> +    // only display if credential_process, source_profile are defined or has valid credentials
// only display in the presence of credential_process, source_profile or valid credentials

2023-02-16 08:30 UTC, luiscamaral commented
> 

Testing on **MacOS** Darwin Kernel Version 21.6.0 arm64 still doesn't work for **AWS_PROFILE** using _source_profile_. Need additional test.

2023-02-16 21:21 UTC, devmatteini commented
> Testing on **MacOS** Darwin Kernel Version 21.6.0 arm64 still doesn't work for **AWS_PROFILE** using _source_profile_. Need additional test.

Can you share your `~/.aws/config` to understand why it doesn't work?

2023-02-17 01:16 UTC, luiscamaral commented
> > Testing on **MacOS** Darwin Kernel Version 21.6.0 arm64 still doesn't work for **AWS_PROFILE** using _source_profile_. Need additional test.
> 
> Can you share your `~/.aws/config` to understand why it doesn't work?

Hi @devmatteini, this is it. It was late last night and I didn't noticed I have a `credential_process` on the `source_profile`, and the validation was not checking for this condition.

The easiest way to resolve this for all the previous use cases covered, might be delegating validation to the existing functions `has_credential_process_or_sso` and `has_defined_credentials`.

Something like this:
```rust
fn has_source_profile(
    context: &Context,
    aws_profile: Option<&Profile>,
    aws_config: &AwsConfigFile,
    aws_creds: &AwsCredsFile,
) -> Option<bool> {
    let config = get_config(context, aws_config)?;
    let config_section = get_profile_config(config, aws_profile)?;
    let source_profile = config_section
        .get("source_profile")
        .map(std::borrow::ToOwned::to_owned);

    Some(
        has_credential_process_or_sso(context, source_profile.as_ref(), &aws_config, &aws_creds)
        .unwrap_or(false)
        || has_defined_credentials(context, source_profile.as_ref(), &aws_creds).unwrap_or(false)
    )
```

* Tested on **MacOS** Darwin Kernel Version 21.6.0 arm64 (apple silicon).

2023-02-17 19:29 UTC, luiscamaral commented
> If I'm understanding, you have a config file that looks like this:
> 
> ```
> [profile starship]
> credential_process = /opt/bin/awscreds-retriever --username starship
> 
> [profile astronauts]
> source_profile = starship
> ```

Yes, that is the type of credential I have. 

Off course it carry a bit more details. For example a default region, or what role to assume in another account. For example:
 
``` AsciiDoc
[profile starship]
region = us-east-1
credential_process = ~/bin/awscreds --username starship --account 999888777666 --json

[profile astronauts:west]
region = us-west-2
role_arn = arn:aws:iam::111222333444:role/EngineeringAccessRole
source_profile = starship
```

2023-02-18 15:28 UTC, devmatteini commented
@luiscamaral Now `source_profile` should also works with `credential_process`

2023-02-18 19:52 UTC, luiscamaral commented
> @luiscamaral Now `source_profile` should also works with `credential_process` 👍🏻 

Thank you @devmatteini 🔍

2023-02-18 19:53 UTC, luiscamaral approved these changes
Tested and working all cases tested on MacOS Darwin Kernel Version 21.6.0 arm64!

<details>
  <summary>co-author [click here]</summary>
  @devmatteini 
  Would you mind to add me as a <a href="https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors"><b>co-author</b></a> on this commit? (@luiscamaral)
</details>

2023-02-19 13:56 UTC, devmatteini commented
> @devmatteini Would you mind to add me as a co-author on this commit? (@luiscamaral)

Sure no problem

2023-03-28 07:11 UTC, davidkna approved these changes

2023-04-02 14:38 UTC, merged

2023-04-02 14:38 UTC, andytom commented
Thank you for your contribution @devmatteini.