feat(color): add prevfg,prevbg as color specifiers based on the previous foreground/background colors respectively
starship/starship pull request #4945
Opened 2023-02-27 20:17 UTC by vladimir-lu

#### Description

#### Motivation and Context

Closes #

#### Screenshots (if appropriate):

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

2023-02-27 20:43 UTC, vladimir-lu commented
https://github.com/vladimir-lu/starship-theme-powerline is an example config that can be used for manual testing

2023-04-07 13:37 UTC, davidkna requested changes
Sorry for not reviewing this earlier, but this PR required more attention compared to other PRs.
I found a few issues, but the changes work surprisingly well with fairly few code changes, thank you for contributing this!

2023-04-07 13:37 UTC, davidkna commented on src/module.rs
> +                current.push(segment.ansi_string(current.last().map(|s| s.style_ref())));
I think it would be simpler to always store the last `Style` in a variable.

2023-05-11 09:44 UTC, CEbbinghaus commented
This looks awesome. Glad to see that we are finally getting this functionality. Comments seem reasonable so is there anything preventing this from progressing further?

2024-04-27 17:49 UTC, MartenBE commented
Is there any update on this? This would be very handy to change from powerline to starship

2024-06-28 21:40 UTC, closed without merging