feat(git_metrics) add option to ignore submodules
starship/starship pull request #5052
Opened 2023-04-01 23:30 UTC by cdmistman

#### Description

There's an option in [`git_status`](https://starship.rs/config/#git-status) to ignore git submodules, this does the same for the `git_diff` module.

#### Motivation and Context

I have a repository with a Very Large Git Submodule™️ causing the git_metrics module to not show in my starship prompt due to the starship timeout configuration. It's inconvenient having the prompt not paint for ~300ms (my timeout configuration) so this adds a configuration option to the `git_metrics` module to pass the `--ignore-submodules` flag to `git diff`.

#### Screenshots (if appropriate):
N/A

#### How Has This Been Tested?

- [x] I have tested using **MacOS**
  - (I'm using Nix, so I'm omitting irrelevant steps)
  - Add `git_metrics.ignore_submodules = true` to my starship config
  - Build my edited version of starship
  - `export PATH="/path/to/starship/repo/target/debug:$PATH"`
  - `eval $(starship init zsh)`
  - noticed presence of git metrics module
  - `starship timings` showed the module took 15ms to render
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [x] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

2023-04-02 11:51 UTC, davidkna requested changes
Please try adding a test for this, even if it only confirms that the module still works after the change.

2023-04-02 21:07 UTC, cdmistman commented
Added a test that's redundant of another test, except adds the `ignore_submodules = true` configuration. I'll note that the `git_status` module doesn't test at all with `ignore_submodules = true`.

For posterity: Git bans local repositories from being submodules (submodules must have a valid networked remote), so this feature can't be tested without pulling the starship repo on every `cargo test`, which will add *lots* of time to the test suite.

2023-04-03 08:48 UTC, davidkna approved these changes

2023-04-13 19:04 UTC, merged

2023-04-13 19:04 UTC, davidkna commented
Thanks for implementing this @cdmistman!