fix(presets) Added ($style) to format in module 'sudo' in Bracketed Segments Preset
starship/starship pull request #5146
Opened 2023-04-27 17:15 UTC by e-khurmamatov

#### Description
There was no ($style) in format for module `sudo`. I added it. 

#### Motivation and Context
`sudo` module is not working by default when Bracketed Segments preset used. 

#### Screenshots:
Before changes
<img width="892" alt="before changes" src="https://user-images.githubusercontent.com/74624554/234937595-87bc9ea4-c4ee-4e38-a3cd-5caafbf3512c.png">
After changes
<img width="892" alt="image" src="https://user-images.githubusercontent.com/74624554/234938395-425786d5-de6d-4c89-9fa8-eb778307d98d.png">

#### How Has This Been Tested?

- [x] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

2023-04-29 09:43 UTC, davidkna requested changes

2023-04-29 09:43 UTC, davidkna commented on docs/.vuepress/public/presets/toml/bracketed-segments.toml
> +format = '\[[as $symbol($style)]\]'
With your change, the syntax was still invalid:
```suggestion
format = '\[[as $symbol]($style)\]'
```

2023-04-29 10:14 UTC, davidkna approved these changes

2023-04-29 14:35 UTC, mickimnet approved these changes

2023-04-30 19:16 UTC, e-khurmamatov commented on docs/.vuepress/public/presets/toml/bracketed-segments.toml
> +format = '\[[as $symbol($style)]\]'
> There is a typo–`($style)` belongs behind the `]`. Like: `\[[as $symbol]($style)\]`

Fixed in previous requested changes. Sorry for typo :)

2023-05-01 20:14 UTC, merged

2023-05-01 20:14 UTC, andytom commented
Thank you for your contribution @e-khurmamatov and thank you reviewing @davidkna and @mickimnet.