feat(aws): support aws sso with automatic authentication refresh
starship/starship pull request #5170
Opened 2023-05-05 14:52 UTC by kensasongko

#### Description
Currently starship supports AWS SSO with 
[legacy non-refreshable configuration](https://docs.aws.amazon.com/cli/latest/userguide/sso-configure-profile-legacy.html).

This PR adds a support for the newer and recommended configuration for AWS CLI to authenticate AWS SSO with 
[automatic authentication refresh](https://docs.aws.amazon.com/cli/latest/userguide/sso-configure-profile-token.html).

Example of the config file with refreshable token (taken from their documentation):
`[profile my-dev-profile]
sso_session = my-sso
sso_account_id = 123456789011
sso_role_name = readOnly
region = us-west-2
output = json

[sso-session my-sso]
sso_region = us-east-1
sso_start_url = https://my-sso-portal.awsapps.com/start
sso_registration_scopes = sso:account:access`

#### How Has This Been Tested?
- [ ] I have tested using **MacOS**
- [x] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:
- [ ] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

2023-05-05 17:07 UTC, davidkna requested changes
Please also update the module docs in `docs/config/README.md`

2023-05-06 01:51 UTC, kensasongko commented
> Please also update the module docs in `docs/config/README.md`

Updated.

2023-05-06 06:50 UTC, davidkna approved these changes

2023-05-09 05:53 UTC, merged

2023-05-09 05:54 UTC, andytom commented
Thank you for your contribution @kensasongko and thank you for reviewing @davidkna.