docs: Fix Arch Linux Repo Name
starship/starship pull request #5243
Opened 2023-06-12 16:39 UTC by Dosenpfand

Adapt Arch Linux repo link from community to extra.

#### Description

Arch Linux has moved the `[community]` repo into the `[extra]`, see https://archlinux.org/news/git-migration-completed/
This PR adapts the links accordingly so that no 404 occurs anymore.

#### Motivation and Context

Get rid of dead links.

#### Screenshots (if appropriate):

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [x] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

2023-06-12 16:59 UTC, davidkna requested changes
Please only update the English docs to avoid conflicts with Crowdin. The translated docs will be updated automatically.

2023-06-13 08:01 UTC, Dosenpfand commented
@davidkna , sorry should have checked before that they should not be edited directly. Reverted.

2023-06-14 07:46 UTC, davidkna approved these changes

2023-06-14 07:46 UTC, merged

2023-06-14 07:46 UTC, davidkna commented
Thanks for the fix!