feat: jj: add jj current change ID
starship/starship pull request #5814
Opened 2024-03-02 12:46 UTC by poliorcetics

#### Description

Adds support for getting and displaying the current Jujutsu change ID (when in a Jujutsu repo)

#### Motivation and Context

[Jujutsu](https://github.com/martinvonz/jj) is a new VCS that is change-based.

I want to do several PRs to add various parts of its informations to starship, starting with the  simplest one, the current change ID.

#### Screenshots (if appropriate):

Explained prompt, with the JJ change ID module:

![Screenshot 2024-03-02 at 13 45 29](https://github.com/starship/starship/assets/7951708/ecef8cab-bd95-42fc-916e-550dcf4879a5)

Result of explained prompt above:

![Screenshot 2024-03-02 at 13 45 50](https://github.com/starship/starship/assets/7951708/c872463a-c372-42f0-b5aa-8926079ab1fd)

#### How Has This Been Tested?

- [x] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [x] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

2024-03-02 14:45 UTC, poliorcetics commented
I see #5772 exists, it uses the approach of computing everything at once and only displaying the wanted elements, I'm not sure which starship prefers

2024-03-02 14:53 UTC, necauqua commented
I'd strongly prefer the jj calls would have `--ignore-working-copy` to avoid snapshots being made literally on every prompt. Somebody might want it I guess, but at least make it configurable then.

Not snapshotting works fine for change ids and branches, for diffs you'd either give up and do snapshots or wait for `--no--commit-transaction` option to be a thing

2024-03-02 15:11 UTC, poliorcetics commented
@necauqua you're right, and `--ignore-working-copy` is much faster too.

I also added the `--repository`, I though it would interfere with testing but since I mocked `jj root` too, it doesn't :tada:

The step has gone from 48ms before to 35ms with those

2024-04-03 02:23 UTC, ckoehler commented
Would love to also be able to indicate whether the change is empty or missing a description. Thanks! Happy to help move this along...

2024-06-10 18:35 UTC, davidkna requested changes

2024-06-10 18:35 UTC, davidkna commented on src/context.rs
> +                let out = self.exec_cmd("jj", &["root", "--ignore-working-copy"])?;
I think it might be better to do `begin_ancestor_scan` first for better performance.

2024-11-09 00:18 UTC, poliorcetics commented
Closing because I started work on https://github.com/starship/starship/issues/5932 instead

2024-11-09 00:18 UTC, closed without merging