feat: support opentofu for terraform version detection
starship/starship pull request #6072
Opened 2024-07-06 14:13 UTC by bojanrajkovic

#### Description

Adds support for detecting the Terraform version when OpenTofu is used instead of Hashicorp Terraform.

#### Motivation and Context

I use OpenTofu with my homelab instead of Terraform, and wanted my Starship prompt to show the
version. :)

#### Screenshots (if appropriate):

<img width="650" alt="Screenshot 2024-07-06 at 10 13 23 AM" src="https://github.com/starship/starship/assets/110747/63fe0b80-b0ca-4695-9806-7f2b511e33ee">

#### How Has This Been Tested?

- [x] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

Test changes by both introducing unit tests and running a built version of Starship against
a couple of different Terraform/OpenTofu install setups on macOS. I don't have a Windows
machine handy, but can test on Linux if needed.

#### Checklist:

- [x] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

2024-07-25 11:35 UTC, davidkna requested changes

2024-07-25 11:35 UTC, davidkna commented on src/modules/terraform.rs
> +        .split_whitespace()
Please use `.split_once(' ')` instead.

2024-07-25 11:35 UTC, davidkna commented on src/modules/terraform.rs
> +    Some(version[1..].to_string())
Please keep using `.trim_start_matches('v')`, or at least use `.get(1..)` instead to avoid potential panics.

2024-07-25 11:35 UTC, davidkna commented on src/modules/terraform.rs
> +        let terraform_version = Lazy::new(|| context.exec_cmds_return_first(config.commands));
Is there a reason you are using `Lazy` instead of putting `let terraform_version = context.exec_cmds_return_first(config.commands)` into the `match`?

2024-07-25 11:35 UTC, davidkna commented on docs/config/README.md
> +| `commands`          | `[ [ 'terraform', 'version' ], [ 'tofu', 'version' ] ]` | How to detect what the Terraform version is                               |
```suggestion
| `commands`          | `[ [ 'terraform', 'version' ], [ 'tofu', 'version' ] ]` | How to detect what the Terraform version is.                              |
```

2024-11-21 10:55 UTC, fiskhest commented
Yearning for this, any chance you can address the review @bojanrajkovic ?

2025-08-14 05:49 UTC, jmarianer commented
Bojan has disappeared from the Starship scene, so I revitalized this PR as #6910. I addressed the changes requested by @davidkna last year but am happy to address more if needed. Note that I'm very much a beginner in the Rust arena, feel free to tell me if I'm doing something wrong.

2025-09-06 17:22 UTC, closed without merging