fix(nodejs): detect bun project files
starship/starship pull request #6346
Opened 2024-10-23 15:08 UTC by alex-grover

#### Description

Hide the Node.js prompt by default if Bun project files are detected.

#### Motivation and Context

The current default prompt shows both the Node.js and Bun prompts in Bun projects, because both runtimes use `package.json` to specify dependencies. However, in Bun projects, this file doesn't actually indicate that Node.js is used. This is a common enough use case that it was added to the docs in #5834.

It was suggested that this should be the default behavior in #4298 but was never implemented.

Closes #5805

#### How Has This Been Tested?

I have not tested this but have tested the equivalent behavior via config file

2024-11-02 10:54 UTC, davidkna requested changes
LGTM, but please update the docs at `docs/config/README.md`.

2024-11-05 03:12 UTC, alex-grover commented
@davidkna done!

2025-01-02 12:56 UTC, tharakadesilva commented
Could you also include `bun.lock` here, please? This is with bun's new [text based lock file](https://bun.sh/blog/bun-lock-text-lockfile) (https://github.com/starship/starship/pull/6441)

2025-01-03 16:15 UTC, alex-grover commented
added, thanks for the suggestion @tharakadesilva!

2025-01-04 15:08 UTC, davidkna approved these changes

2025-03-09 18:31 UTC, merged

2025-03-09 18:31 UTC, davidkna commented
Thanks for the contribution @alex-grover!